ALTER TABLE PRESTADORES
    ADD CONSTRAINT FK_PAIS_USARIOS
    FOREIGN KEY( ESTADIO_ID ) 
    REFERENCES ESTADOS_PRESTADORES (ID);


CREATE TABLE PAISES(
ID          NUMBER (10,0) PRIMARY KEY,
NOMBRE_PAIS VARCHAR(250),
ESTADO      VARCHAR(250)
);

CREATE TABLE DEPARTAMENTOS(
ID                   NUMBER(10,0) PRIMARY KEY,
NOMBRE_DEPARTAMENTO  VARCHAR(250),
ID_PAIS              NUMBER(10,0) NOT NULL,
ESTADO               VARCHAR(250)
);

ALTER TABLE DEPARTAMENTOS 
    ADD CONSTRAINT FK_DEPARTAMENTO_PAIS 
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

CREATE TABLE MUNICIPIOS(
ID               NUMBER(10,0) PRIMARY KEY,
NOMBRE_MUNICIPIO VARCHAR(250)
ID_DEPARTAMENTO  NUMBER(10,0) NOT NULL,
ESTADO           VARCHAR(250)
);

ALTER TABLE MUNICIPIOS 
    ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS
	FOREIGN(ID_DEPARTAMENTO)
	REFERENCES DEPARTAMENTOS(ID);

CREATE TABLE ANOS(
ID     NUMBER(10,0) PRIMARY KEY,
ANO    VARCHAR(250),
ESTADO VARCHAR(250)
);

CREATE TABLE MESES(
ID     NUMBER(10,0) PRIMARY KEY,
MES    VARCHAR(250),
ESTADO VARCHAR(250)
);

CREATE TABLE DIAS(
ID     NUMBER(10,0) PRIMARY KEY,
DIA    VARCHAR(250),
ESTADO VARCHAR(250)
);

CREATE TABLE NACIONALIDADES(
ID           NUMBER(10,0) PRIMARY KEY,
NACIONALIDAD VARCHAR(250),
ESTADO       VARCHAR(250)
);

CREATE TABLE ZONAS_HORARIAS(
ID NUMBER(10,0) PRIMARY KEY,
ZONA_HORARIO VARCHAR(250),
ESTADO VARCHAR(250)
);

CREATE TABLE CODIGOS_POSTALES(
ID            NUMBER(10,0) PRIMARY KEY,
CODIGO_POSTAL VARCHAR(250),
ESTADO        VARCHAR(250)
);

CREATE TABLE PREFIJOS(
ID      NUMBER(10,0) PRIMARY KEY,
PREFIJO VARCHAR(250),
ID_PAIS NUMBER(10,0) NOT NULL,
ESTADO  VARCHAR(250)
);

ALTER TABLE PREFIJOS 
    ADD CONSTRAINT FK_PREFIJOS_PAISES
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

CREATE TABLE USUARIOS(
ID         NUMBER(10,0) PRIMARY KEY,
NOMBRE1    VARCHAR(250) NOT NULL,
NOMBRE2    VARCHAR(250),
APELLIDO1  VARCHAR(250) NOT NULL,
APELLIDO2  VARCHAR(250) NOT NULL,
TITULO     VARCHAR(250) NOT NULL,
CONTRASENA VARCHAR(250) NOT NULL,
ESTADO     VARCHAR(250) NOT NULL
);

CREATE TABLE DOCUMENTO_USUARIO(
ID         NUMBER(10,0) PRIMARY KEY,
ID_TIPO    NUMBER(10,0) NOT NULL,
ID_PAIS    NUMBER(10,0) NOT NULL,
ID_ANO     NUMBER(10,0) NOT NULL,
ID_MES     NUMBER(10,0) NOT NULL,
ID_DIA     NUMBER(10,0) NOT NULL,
ID_USUARIO NUMBER(10,0) NOT NULL,
ESTADO     VARCHAR(250)
);

ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_TIPO
	FOREIGN(ID_TIPO)
	REFERENCES TIPOS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_PAIS
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_ANO
	FOREIGN(ID_ANO)
	REFERENCES ANOS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_MES
	FOREIGN(ID_MES)
	REFERENCES MESES(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_DIA
	FOREIGN(ID_DIA)
	REFERENCES DIAS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_USUARIO
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);

CREATE TABLE LIMITES_DEPSITOS_USUARIOS(
ID NUMBER(10,0) PRIMARY KEY,
ID_USUARIO                 NUMBER(10,0) NOT NULL,
LIMITE_DIARIO_ANTERIOR     VARCHAR(250),
LIMITE_DIARIO_ACTUAL       VARCHAR(250),
FECHA_ACTUALIZACION_DIA    TIMESTAMP,
LIMITE_SEMANA_ANTERIOR     VARCHAR(250),
LIMITE_SEMANA_ACTUAL       VARCHAR(250),
FECHA_ACTUALIZACION_SEMANA TIMESTAMP,
LIMITE_MENSUAL_ANTERIOR    VARCHAR(250),
LIMITE_MENSUAL_ACTUAL      VARCHAR(250),
FECHA_ACTUALIZACION_MES    TIMESTAMP,
ESTADO                     VARCHAR(250)
);

ALTER TABLE LIMITES_DEPSITOS_USUARIOS 
    ADD CONSTRAINT FK_LIMITES_USUARIOS
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);

CREATE TABLE PREFERENCIAS_USUARIOS(
ID NUMBER(10,0) PRIMARY KEY,
ID_USUARIO NUMBER(10,0) NOT NULL,
ACEPTA_TERMINOS_CONDICIONES BOOLEAN,
ACEPTA_INFORMACION_COMERCIAL BOOLEAN,
ACEPTA_BARRIO BOOLEAN,
ID_BONO NUMBER(10,0),
ACEPTA_BOLETIN_INFORMATIVO BOOLEAN,
ACEPTA_CORREO_APUESTAS BOOLEAN,
ACEPTA_ENVIO_SMS BOOLEAN,
ACEPTA_NOTIFICACIONES BOOLEAN,
ACEPTA_AVISOS_BOLETA_APUESTA BOOLEAN,
LIMITE_APUESTAS_DIARIA NUMBER(10,2),
LIMITE_APUESTAS_SEMANAL NUMBER(10,2),
LIMITE_APUESTAS_MENSUAL NUMBER(10,2),
ESTADO VARCHAR(250)
);

ALTER TABLE PREFERENCIAS_USUARIOS 
    ADD CONSTRAINT FK_PREFENCIAS_USUARIOS_USUARIOS
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);
	
create table datos_contacto_usuario(
id number (10,0) not null,
direccion1 varchar(250),
direccion2 varchar(250),
id_paisrec number (10,0)not null,
id_dpto number (10,0)not null,
id_muni number (10,0)not null,
id_codpos number (10,0)not null,
id_prefijo number (10,0)not null,
numcel varchar(250),
email varchar(250),
idioma_email varchar(250),
id_preferencia number (10,0)not null,
estado varchar(250),
CONSTRAINT datos_contacto_usuario_pk PRIMARY KEY (id),
CONSTRAINT  fk_paisrec        foreign key (id_paisrec)     references paises(id),
CONSTRAINT  fk_dptorec        foreign key (id_dpto)        references departamento(id),
CONSTRAINT  fk_munirec        foreign key (id_muni)        references municipios(id),
CONSTRAINT  fk_codposrec      foreign key (id_codpos)      references codigo_postal(id),
CONSTRAINT  fk_prefijorec     foreign key (id_prefijo)     references prefijos(id),
CONSTRAINT  fk_preferenciarec foreign key (id_preferencia) references preferencias_usuarios(id)
);

CREATE TABLE DATOS_CONTACTOS_USUARIOS(
ID              NUMBER(10,0) PRIMARY KEY,
DIRECCION1      VARCHAR(250) NOT NULL,
DIRECCION2      VARCHAR(250),
ID_PAIS         NUMBER(10,0) NOT NULL,
ID_DEPARTAMENTO NUMBER(10,0) NOT NULL,
ID_MUNICIPIO    NUMBER(10,0) NOT NULL,
ID_PREFIJO      NUMBER(10,0) NOT NULL,
CELULAR         VARCHAR(250) NOT NULL,
EMAIL           VARCHAR(250) NOT NULL,
IDIOMA_EMAIL    VARCHAR(250) NOT NULL,
ID_PREFERENCIA  NUMBER(10,0) NOT NULL,
ESTADO          VARCHAR(250)
);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PAIS
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_DEPARTAMENTO
	FOREIGN(ID_DEPARTAMENTO)
	REFERENCES DEPARTAMENTOS(ID);
	
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_MUNICIPIO
	FOREIGN(ID_MUNICIPIO)
	REFERENCES MUNICIPIOS(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PREFIJOS
	FOREIGN(ID_PREFIJO)
	REFERENCES PREFIJOS(ID);
	
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PREFERENCIAS
	FOREIGN(ID_PREFERENCIA)
	REFERENCES PREFERENCIAS_USUARIOS(ID);






















	





