ALTER TABLE DEPARTAMENTOS 
    ADD CONSTRAINT FK_DEPARTAMENTO_PAIS 
    FOREIGN KEY(ID_PAIS)
	  REFERENCES PAISES(ID);

ALTER TABLE MUNICIPIOS 
    ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS
	  FOREIGN KEY(ID_DEPARTAMENTO)
	  REFERENCES DEPARTAMENTOS(ID);

ALTER TABLE PREFIJOS 
    ADD CONSTRAINT FK_PREFIJOS_PAISES
	  FOREIGN KEY(ID_PAIS)
	  REFERENCES PAISES(ID);

ALTER TABLE DOCUMENTOS_USUARIOS
    ADD CONSTRAINT FK_DOCUMENTO_TIPO
	  FOREIGN KEY(ID_TIPO)
	  REFERENCES TIPOS_DOCUMENTOS_USUARIOS(ID);
	
ALTER TABLE DOCUMENTOS_USUARIOS 
    ADD CONSTRAINT FK_DOCUMENTO_PAIS
	  FOREIGN KEY(ID_PAIS)
	  REFERENCES PAISES(ID);

ALTER TABLE DOCUMENTOS_USUARIOS 
    ADD CONSTRAINT FK_DOCUMENTO_ANO
	  FOREIGN KEY(ID_ANO)
	  REFERENCES ANOS(ID);
	
ALTER TABLE DOCUMENTOS_USUARIOS 
    ADD CONSTRAINT FK_DOCUMENTO_MES
	  FOREIGN KEY(ID_MES)
	  REFERENCES MESES(ID);
	
ALTER TABLE DOCUMENTOS_USUARIOS 
    ADD CONSTRAINT FK_DOCUMENTO_DIA
	  FOREIGN KEY(ID_DIA)
	  REFERENCES DIAS(ID);
	
ALTER TABLE DOCUMENTOS_USUARIOS 
    ADD CONSTRAINT FK_DOCUMENTO_USUARIO
	  FOREIGN KEY(ID_USUARIO)
	  REFERENCES USUARIOS(ID);

ALTER TABLE LIMITES_DEPOSITOS_USUARIOS 
    ADD CONSTRAINT FK_LIMITES_USUARIOS
	  FOREIGN KEY(ID_USUARIO)
	  REFERENCES USUARIOS(ID);

ALTER TABLE PREFERENCIAS_USUARIOS 
    ADD CONSTRAINT FK_PREFENCIAS_USUARIOS_USU
	  FOREIGN KEY(ID_USUARIO)
    REFERENCES USUARIOS(ID);
    
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PAIS
	  FOREIGN KEY(ID_PAIS)
	  REFERENCES PAISES(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_DEPART
	  FOREIGN KEY(ID_DEPARTAMENTO)
	  REFERENCES DEPARTAMENTOS(ID);
	
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_MUNICIPIO
	  FOREIGN KEY(ID_MUNICIPIO)
	  REFERENCES MUNICIPIOS(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PREFIJOS
	  FOREIGN KEY(ID_PREFIJO)
	  REFERENCES PREFIJOS(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_USUARIO
	  FOREIGN KEY(ID_USUARIO)
	  REFERENCES USUARIOS(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_NACIONALIDAD
	  FOREIGN KEY(ID_NACIONALIDAD)
	  REFERENCES NACIONALIDADES(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_ANO
	  FOREIGN KEY(ID_ANO)
	  REFERENCES ANOS(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_MES
	  FOREIGN KEY(ID_MES)
	  REFERENCES MESES(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_DIA
	  FOREIGN KEY(ID_DIA)
	  REFERENCES DIAS(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_ZONA_HORARIA
	  FOREIGN KEY(ID_ZONA_HORARIA)
	  REFERENCES ZONAS_HORARIAS(ID);

ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_APUESTAS
	  FOREIGN KEY(ID_APUESTA)
	  REFERENCES APUESTAS(ID);
	
ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_CUOTA
	  FOREIGN KEY(ID_CUOTA)
	  REFERENCES CUOTAS(ID);

ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_ESTADO
	  FOREIGN KEY(ID_ESTADO_APUESTA)
	  REFERENCES ESTADOS_APUESTAS(ID);

ALTER TABLE CUOTAS 
    ADD CONSTRAINT FK_CUOTAS_PARTIDO
	  FOREIGN KEY(ID_PARTIDO)
	  REFERENCES PARTIDOS(ID);
	
ALTER TABLE CUOTAS 
    ADD CONSTRAINT FK_CUOTAS_TIPOS_APUESTAS
	  FOREIGN KEY(ID_TIPO_APUESTA)
	  REFERENCES TIPOS_APUESTAS(ID);

ALTER TABLE LIMITES_APUESTAS_USUARIOS 
    ADD CONSTRAINT FK_LIMITES_APUESTAS_ESTADO
	  FOREIGN KEY(ID_USUARIO)
	  REFERENCES USUARIOS(ID);

ALTER TABLE PARTIDOS 
    ADD CONSTRAINT FK_PARTIDOS_LOCAL
	  FOREIGN KEY(ID_EQUIPO_LOCAL)
	  REFERENCES EQUIPOS_APUESTAS(ID);
    
ALTER TABLE DEPOSITOS
    ADD CONSTRAINT FK_DEPOSITOS_USUARIO
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES USUARIOS(ID);
    
ALTER TABLE RETIROS
    ADD CONSTRAINT FK_RETIROS_USUARIOS 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES USUARIOS(ID);
    
ALTER TABLE RETIROS 
    ADD CONSTRAINT FK_REQUISITOS_DESEMBOLSO 
    FOREIGN KEY (ID_REQUSITOS_DESEMBOLSO) 
    REFERENCES REQUISITOS_DESEMBOLSO(ID);

ALTER TABLE REQUISITOS_DESEMBOLSO
    ADD CONSTRAINT FK_REQUISITOS_DESEMBOLSO_USU
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES USUARIOS(ID); 
    
ALTER TABLE APUESTAS
    ADD CONSTRAINT FK_APUESTA_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID);
    
ALTER TABLE PREFERENCIAS_USUARIOS
    ADD CONSTRAINT FK_BONO_USUARIO
    FOREIGN KEY (ID_BONO)
    REFERENCES BONOS(ID);
    
ALTER TABLE PREFERENCIAS_USUARIOS
    ADD CONSTRAINT FK_BONO_USUARIO
    FOREIGN KEY (ID_BONO)
    REFERENCES BONOS(ID);
    
ALTER TABLE DATOS_CONTACTOS_USUARIOS
    ADD CONSTRAINT FK_CONTACTO_CODIGO_POST
    FOREIGN KEY (ID_CODIGO_POSTAL)
    REFERENCES CODIGOS_POSTALES(ID);
    
ALTER TABLE DATOS_CONTACTOS_USUARIOS
    ADD CONSTRAINT FK_CONTACTO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID);
    
ALTER TABLE DEPOSITOS
    ADD CONSTRAINT FK_DEPOSITOS_ESTADO
    FOREIGN KEY (ID_ESTADO_DEPOSITO)
    REFERENCES ESTADOS_DEPOSITOS(ID);

ALTER TABLE DEPOSITOS
    ADD CONSTRAINT FK_DEPOSITOS_MEDIOS_PAG
    FOREIGN KEY (ID_MEDIOPAGO)
    REFERENCES TIPO_MEDIOS_PAGOS(ID);

ALTER TABLE LIMITES_APUESTAS_USUARIOS
    ADD CONSTRAINT FK_LIMITE_APUESTAS_USUAR
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID);

    

    
    
