ALTER TABLE DEPARTAMENTOS 
    ADD CONSTRAINT FK_DEPARTAMENTO_PAIS 
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE MUNICIPIOS 
    ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS
	FOREIGN(ID_DEPARTAMENTO)
	REFERENCES DEPARTAMENTOS(ID);

ALTER TABLE PREFIJOS 
    ADD CONSTRAINT FK_PREFIJOS_PAISES
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_TIPO
	FOREIGN(ID_TIPO)
	REFERENCES TIPOS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_PAIS
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_ANO
	FOREIGN(ID_ANO)
	REFERENCES ANOS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_MES
	FOREIGN(ID_MES)
	REFERENCES MESES(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_DIA
	FOREIGN(ID_DIA)
	REFERENCES DIAS(ID);
	
ALTER TABLE DOCUMENTO_USUARIO 
    ADD CONSTRAINT FK_DOCUMENTO_USUARIO
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);

ALTER TABLE LIMITES_DEPOSITOS_USUARIOS 
    ADD CONSTRAINT FK_LIMITES_USUARIOS
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);

ALTER TABLE PREFERENCIAS_USUARIOS 
    ADD CONSTRAINT FK_PREFENCIAS_USUARIOS_USUARIOS
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PAIS
	FOREIGN(ID_PAIS)
	REFERENCES PAISES(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_DEPARTAMENTO
	FOREIGN(ID_DEPARTAMENTO)
	REFERENCES DEPARTAMENTOS(ID);
	
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_MUNICIPIO
	FOREIGN(ID_MUNICIPIO)
	REFERENCES MUNICIPIOS(ID);

ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PREFIJOS
	FOREIGN(ID_PREFIJO)
	REFERENCES PREFIJOS(ID);
	
ALTER TABLE DATOS_CONTACTOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_CONTACTOS_PREFERENCIAS
	FOREIGN(ID_PREFERENCIA)
	REFERENCES PREFERENCIAS_USUARIOS(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_USUARIO
	FOREIGN(ID_USUARIO)
	REFERENCES USUARIOS(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_NACIONALIDAD
	FOREIGN(ID_NACIONALIDAD)
	REFERENCES NACIONALIDADES(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_ANO
	FOREIGN(ID_ANO)
	REFERENCES ANOS(ID);

ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_MES
	FOREIGN(ID_MES)
	REFERENCES MESES(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_DIA
	FOREIGN(ID_DIA)
	REFERENCES DIAS(ID);
	
ALTER TABLE DATOS_USUARIOS 
    ADD CONSTRAINT FK_DATOS_USUARIOS_ZONA_HORARIA
	FOREIGN(ID_ZONA_HORARIA)
	REFERENCES ZONAS_HORARIAS(ID);

ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_APUESTAS
	FOREIGN(ID_APUESTA)
	REFERENCES APUESTAS(ID);
	
ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_CUOTA
	FOREIGN(ID_CUOTA)
	REFERENCES CUOTAS(ID);

ALTER TABLE DETALLES_APUESTAS 
    ADD CONSTRAINT FK_DETALLES_APUESTAS_ESTADO
	FOREIGN(ID_ESTADO_APUESTA)
	REFERENCES ESTADOS_APUESTAS(ID);

ALTER TABLE CUOTAS 
    ADD CONSTRAINT FK_CUOTAS_PARTIDO
	FOREIGN(ID_PARTIDO)
	REFERENCES PARTIDOS(ID);
	
ALTER TABLE CUOTAS 
    ADD CONSTRAINT FK_CUOTAS_TIPOS_APUESTAS
	FOREIGN(ID_TIPO_APUESTA)
	REFERENCES TIPOS_APUESTAS(ID);

ALTER TABLE LIMITES_APUESTAS_USUARIOS 
    ADD CONSTRAINT FK_LIMITES_APUESTAS_USUARIOS_ESTADO
	FOREIGN(ID_LIMITES_APUESTAS)
	REFERENCES LIMITES_APUESTAS_USUARIOS(ID);

ALTER TABLE PARTIDOS 
    ADD CONSTRAINT FK_PARTIDOS_LOCAL
	FOREIGN(ID_EQUIPO_LOCAL)
	REFERENCES EQUIPOS_APUESTAS(ID);

ALTER TABLE PARTIDOS 
    ADD CONSTRAINT FK_PARTIDOS_VISITANTE
	FOREIGN(ID_EQUIPO_VISITANTE)
	REFERENCES EQUIPOS_APUESTAS(ID);