CREATE TABLE PAISES(
ID          NUMBER (10,0) PRIMARY KEY,
NOMBRE_PAIS VARCHAR(250),
ESTADO      VARCHAR(250) NOT NULL
);

CREATE TABLE DEPARTAMENTOS(
ID                   NUMBER(10,0) PRIMARY KEY,
NOMBRE_DEPARTAMENTO  VARCHAR(250),
ID_PAIS              NUMBER(10,0) NOT NULL,
ESTADO               VARCHAR(250) NOT NULL
);

CREATE TABLE MUNICIPIOS(
ID               NUMBER(10,0) PRIMARY KEY,
NOMBRE_MUNICIPIO VARCHAR(250)
ID_DEPARTAMENTO  NUMBER(10,0) NOT NULL,
ESTADO           VARCHAR(250) NOT NULL 
);

CREATE TABLE ANOS(
ID     NUMBER(10,0) PRIMARY KEY,
ANO    VARCHAR(250),
ESTADO VARCHAR(250) NOT NULL
);
CREATE TABLE MESES(
ID     NUMBER(10,0) PRIMARY KEY,
MES    VARCHAR(250),
ESTADO VARCHAR(250) NOT NULL
);

CREATE TABLE DIAS(
ID     NUMBER(10,0) PRIMARY KEY,
DIA    VARCHAR(250),
ESTADO VARCHAR(250) NOT NULL
);

CREATE TABLE NACIONALIDADES(
ID           NUMBER(10,0) PRIMARY KEY,
NACIONALIDAD VARCHAR(250),
ESTADO       VARCHAR(250) NOT NULL
);

CREATE TABLE ZONAS_HORARIAS(
ID NUMBER(10,0) PRIMARY KEY,
ZONA_HORARIO VARCHAR(250),
ESTADO VARCHAR(250) NOT NULL
);

CREATE TABLE CODIGOS_POSTALES(
ID            NUMBER(10,0) PRIMARY KEY,
CODIGO_POSTAL VARCHAR(250),
ESTADO        VARCHAR(250) NOT NULL
);

CREATE TABLE PREFIJOS(
ID      NUMBER(10,0) PRIMARY KEY,
PREFIJO VARCHAR(250),
ID_PAIS NUMBER(10,0) NOT NULL,
ESTADO  VARCHAR(250) NOT NULL
);

CREATE TABLE USUARIOS(
ID         NUMBER(10,0) PRIMARY KEY,
NOMBRE1    VARCHAR(250) NOT NULL,
NOMBRE2    VARCHAR(250),
APELLIDO1  VARCHAR(250) NOT NULL,
APELLIDO2  VARCHAR(250) NOT NULL,
TITULO     VARCHAR(250) NOT NULL,
CONTRASENA VARCHAR(250) NOT NULL,
ESTADO     VARCHAR(250) NOT NULL
);

CREATE TABLE DOCUMENTO_USUARIO(
ID         NUMBER(10,0) PRIMARY KEY,
ID_TIPO    NUMBER(10,0) NOT NULL,
ID_PAIS    NUMBER(10,0) NOT NULL,
ID_ANO     NUMBER(10,0) NOT NULL,
ID_MES     NUMBER(10,0) NOT NULL,
ID_DIA     NUMBER(10,0) NOT NULL,
ID_USUARIO NUMBER(10,0) NOT NULL,
ESTADO     VARCHAR(250) NOT NULL
);

CREATE TABLE LIMITES_DEPSITOS_USUARIOS(
ID NUMBER(10,0) PRIMARY KEY,
ID_USUARIO                 NUMBER(10,0) NOT NULL,
LIMITE_DIARIO_ANTERIOR     VARCHAR(250),
LIMITE_DIARIO_ACTUAL       VARCHAR(250),
FECHA_ACTUALIZACION_DIA    TIMESTAMP,
LIMITE_SEMANA_ANTERIOR     VARCHAR(250),
LIMITE_SEMANA_ACTUAL       VARCHAR(250),
FECHA_ACTUALIZACION_SEMANA TIMESTAMP,
LIMITE_MENSUAL_ANTERIOR    VARCHAR(250),
LIMITE_MENSUAL_ACTUAL      VARCHAR(250),
FECHA_ACTUALIZACION_MES    TIMESTAMP,
ESTADO                     VARCHAR(250) NOT NULL
);

CREATE TABLE PREFERENCIAS_USUARIOS(
ID NUMBER(10,0) PRIMARY KEY,
ID_USUARIO NUMBER(10,0) NOT NULL,
ACEPTA_TERMINOS_CONDICIONES BOOLEAN,
ACEPTA_INFORMACION_COMERCIAL BOOLEAN,
ACEPTA_BARRIO BOOLEAN,
ID_BONO NUMBER(10,0),
ACEPTA_BOLETIN_INFORMATIVO BOOLEAN,
ACEPTA_CORREO_APUESTAS BOOLEAN,
ACEPTA_ENVIO_SMS BOOLEAN,
ACEPTA_NOTIFICACIONES BOOLEAN,
ACEPTA_AVISOS_BOLETA_APUESTA BOOLEAN,
LIMITE_APUESTAS_DIARIA NUMBER(10,2),
LIMITE_APUESTAS_SEMANAL NUMBER(10,2),
LIMITE_APUESTAS_MENSUAL NUMBER(10,2),
ESTADO VARCHAR(250) NOT NULL
);

CREATE TABLE DATOS_CONTACTOS_USUARIOS(
ID              NUMBER(10,0) PRIMARY KEY,
DIRECCION1      VARCHAR(250) NOT NULL,
DIRECCION2      VARCHAR(250),
ID_PAIS         NUMBER(10,0) NOT NULL,
ID_DEPARTAMENTO NUMBER(10,0) NOT NULL,
ID_MUNICIPIO    NUMBER(10,0) NOT NULL,
ID_PREFIJO      NUMBER(10,0) NOT NULL,
CELULAR         VARCHAR(250) NOT NULL,
EMAIL           VARCHAR(250) NOT NULL,
IDIOMA_EMAIL    VARCHAR(250) NOT NULL,
ID_PREFERENCIA  NUMBER(10,0) NOT NULL,
ESTADO          VARCHAR(250) NOT NULL
);